version: '3.0'
services:
  php:
    # image: php:7.2-apache # remember to comment this line
    container_name: php8.0-apache
    build: .
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html/
